/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module "vue" {
  export interface GlobalComponents {
    DefaultLayout: typeof import("./src/components/DefaultLayout.vue")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
    VanGrid: typeof import("vant/es")["Grid"];
    VanGridItem: typeof import("vant/es")["GridItem"];
  }
}
